name: Spectrum
version: 0.0.19
main: cooldogedev\Spectrum\Spectrum
api: [5.0.0]
author: cooldogedev
description: Spectrum is an implementation of the Spectrum proxy for PocketMine-MP
website: https://github.com/cooldogedev/spectrum-pm
src-namespace-prefix: cooldogedev